//! Zed tree-sitter grammar (`editors/zed/grammars/tree-sitter-eventb`) and its
//! highlight queries (`editors/zed/languages/eventb/highlights.scm`).
//!
//! Zed is the only editor that needs a tree-sitter grammar rather than a regex
//! highlighter, but it only needs a *lexical* one: a parser that recognises each
//! coloured token class as its own node. We generate exactly that — the token
//! rules — into `grammar.js`'s marked region, and the `highlights.scm`
//! node→capture mapping whole-file. The grammar's surrounding scaffold
//! (`source_file`, `identifier`, `number`, `string`, `comment`, `label`,
//! punctuation, `extras`, `word`) is hand-maintained, since it is fixed
//! structure rather than token data.
//!
//! ## Why one node per (class, kind), and no `prec`
//!
//! tree-sitter's lexer breaks ties **by precedence first, then by length**. So
//! `token(prec(1, …))` on a keyword would make `mod` win over the longer
//! `model` (stealing its prefix) and `/` win over the `//` comment. We therefore
//! emit *no* precedence and let plain longest-match do the work: `model` (the
//! identifier) is longer than `mod`, and `//…` (the comment) is longer than `/`.
//!
//! For the one case longest-match cannot settle — an exact-length tie like
//! `context` (keyword) vs `context` (identifier) — the grammar declares
//! `word: $ => $.identifier`, enabling tree-sitter's keyword extraction, which
//! resolves a whole-word match to the keyword. Keyword extraction only applies
//! to *pure word* tokens, so each class is split into a `*_word` node (a
//! case-insensitive regex, extractable) and a `*_sym` node (exact string
//! literals that never collide with identifiers). Within one word regex JS
//! alternation is leftmost — not longest — so the spellings are sorted
//! longest-first (`events` before `event`). Symbol literals need no ordering
//! (the lexer's longest-match picks `<=>` over `<`) and no escaping.

use super::{Markers, MatchKind, Model, Scope, TokenGroup};

/// The generated region inside the otherwise hand-maintained `grammar.js`.
pub const MARKERS: Markers = Markers {
    begin: "// >>> rossi gen-grammars (generated, do not edit)",
    end: "// <<< rossi gen-grammars",
};

/// The tree-sitter node (rule) name a coloured class is emitted as, split by
/// match kind so word nodes stay pure (keyword-extractable) and symbol nodes
/// stay free of identifier collisions. The hand-maintained `_token` rule in
/// `grammar.js` lists exactly these names, and [`render_highlights`] captures
/// them — so a new [`Scope`] variant breaks this `match` until it is handled.
pub fn node_name(scope: Scope, kind: MatchKind) -> &'static str {
    match (scope, kind) {
        (Scope::KeywordControl, _) => "keyword",
        (Scope::KeywordOther, _) => "status_keyword",
        (Scope::SupportFunction, _) => "builtin",
        (Scope::ConstantLanguage, MatchKind::Word) => "constant_word",
        (Scope::ConstantLanguage, MatchKind::Symbol) => "constant_sym",
        (Scope::KeywordOperator, MatchKind::Word) => "operator_word",
        (Scope::KeywordOperator, MatchKind::Symbol) => "operator_sym",
    }
}

/// The Zed/tree-sitter highlight capture a class maps to in `highlights.scm` (a
/// Helix/nvim-treesitter capture name Zed resolves to a theme style). The
/// generated grammar splits each class into a `*_word` and/or `*_sym` node (see
/// [`node_name`]); both map to this one capture. Kept beside `node_name` as a
/// renderer-local mapping (not a method on the shared `Scope`), since both are
/// Zed-only — matching how `vim_group` lives in `vim.rs`.
fn zed_capture(scope: Scope) -> &'static str {
    match scope {
        Scope::KeywordControl | Scope::KeywordOther => "keyword",
        Scope::ConstantLanguage => "constant.builtin",
        Scope::SupportFunction => "function.builtin",
        Scope::KeywordOperator => "operator",
    }
}

/// Render the generated token-rule region of `grammar.js` (between the markers).
/// One rule per non-empty model group, in model order. Ends with the closing
/// marker's indentation, which the splice drops from the region itself.
pub fn render_grammar_region(model: &Model) -> String {
    let mut out = String::new();
    for group in &model.groups {
        if group.members.is_empty() {
            continue;
        }
        let name = node_name(group.scope, group.kind);
        out.push_str(&format!("    {name}: $ => {},\n", token_expr(group)));
    }
    out.push_str("    ");
    out
}

/// Render the whole `highlights.scm`: one capture per generated node (locked to
/// [`zed_capture`]) plus the fixed structural captures.
pub fn render_highlights(model: &Model) -> String {
    let mut out = String::new();
    out.push_str(
        "; Generated by `rossi gen-grammars` from the canonical token tables. Do not edit by hand.\n\
         ; The captured node names are produced by editors/zed/grammars/tree-sitter-eventb.\n\n",
    );
    // One capture per non-empty group; `node_name` gives each a distinct node
    // (so does `render_grammar_region`, which relies on the same uniqueness).
    for group in &model.groups {
        if group.members.is_empty() {
            continue;
        }
        let name = node_name(group.scope, group.kind);
        out.push_str(&format!("({}) @{}\n", name, zed_capture(group.scope)));
    }
    out.push_str(
        "\n(comment) @comment\n\
         (string) @string\n\
         (number) @number\n\
         (label) @label\n\
         (identifier) @variable\n\n\
         [\"(\" \")\" \"[\" \"]\" \"{\" \"}\"] @punctuation.bracket\n\
         \",\" @punctuation.delimiter\n",
    );
    out
}

/// The tree-sitter token expression for one group: a case-insensitive,
/// longest-first regex for a word group, or a `choice` of exact string literals
/// for a symbol group. Both are wrapped in `token(…)` so the node is one leaf.
fn token_expr(group: &TokenGroup) -> String {
    match group.kind {
        MatchKind::Word => {
            // JS alternation is leftmost-not-longest, so `events` must precede
            // `event` (see `super::longest_first`).
            let mut words: Vec<&str> = group.members.iter().map(String::as_str).collect();
            words.sort_by(|a, b| super::longest_first(a, b));
            // Escape regex metacharacters before splicing into the `/(?:…)/i`
            // literal. The metacharacter set is identical for Oniguruma and JS
            // RegExp, so we reuse `escape_oniguruma`. Every word member is
            // alphanumeric today (so this is a no-op), but it keeps the word path
            // as safe as the symbol path, which escapes via `js_string`.
            let alts: Vec<String> = words.iter().map(|w| super::escape_oniguruma(w)).collect();
            format!("token(/(?:{})/i)", alts.join("|"))
        }
        MatchKind::Symbol => {
            let lits: Vec<String> = group.members.iter().map(|s| js_string(s)).collect();
            if lits.len() == 1 {
                format!("token({})", lits[0])
            } else {
                format!("token(choice({}))", lits.join(", "))
            }
        }
    }
}

/// A JavaScript double-quoted string literal (with surrounding quotes), escaping
/// the backslash and double-quote a JS string must escape. Operator spellings
/// like `\/`, `/\` and `\` carry backslashes; private-use glyphs pass through raw.
fn js_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        if c == '\\' || c == '"' {
            out.push('\\');
        }
        out.push(c);
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Every generated node name must be referenced by the hand-maintained
    /// `_token` choice in `grammar.js`; otherwise that class would tokenize but
    /// never reach the tree (silent missing highlight). This is the one coupling
    /// between the generated region and the hand-written scaffold, so it is
    /// guarded explicitly.
    fn grammar_js() -> String {
        let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../editors/zed/grammars/tree-sitter-eventb/grammar.js");
        std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()))
    }

    #[test]
    fn generated_nodes_are_listed_in_token_choice() {
        let model = Model::build();
        let grammar = grammar_js();
        for group in &model.groups {
            if group.members.is_empty() {
                continue;
            }
            let name = node_name(group.scope, group.kind);
            assert!(
                grammar.contains(&format!("$.{name},")),
                "grammar.js `_token` is missing `$.{name}` (generated node has no place in the tree)"
            );
        }
    }

    #[test]
    fn highlights_capture_every_node_and_the_structural_tokens() {
        let model = Model::build();
        let scm = render_highlights(&model);
        for group in &model.groups {
            if group.members.is_empty() {
                continue;
            }
            let name = node_name(group.scope, group.kind);
            let capture = zed_capture(group.scope);
            assert!(
                scm.contains(&format!("({name}) @{capture}\n")),
                "highlights.scm is missing `({name}) @{capture}`"
            );
        }
        for fixed in [
            "(comment) @comment",
            "(string) @string",
            "(number) @number",
            "(label) @label",
            "(identifier) @variable",
            "@punctuation.bracket",
        ] {
            assert!(scm.contains(fixed), "highlights.scm is missing `{fixed}`");
        }
    }

    /// Extract the `|`-separated alternatives from a `token(/(?:…)/i)` rule line.
    fn word_alternatives(region: &str, rule: &str) -> Vec<String> {
        let line = region
            .lines()
            .find(|l| l.trim_start().starts_with(&format!("{rule}:")))
            .unwrap_or_else(|| panic!("missing rule {rule}"));
        let body = line
            .split_once("(?:")
            .and_then(|(_, rest)| rest.split_once(")/i)"))
            .map(|(body, _)| body)
            .unwrap_or_else(|| panic!("rule {rule} is not a `token(/(?:…)/i)` regex: {line}"));
        body.split('|').map(str::to_string).collect()
    }

    #[test]
    fn word_rules_are_longest_first() {
        let model = Model::build();
        let region = render_grammar_region(&model);
        // JS alternation is leftmost-not-longest: within one word regex, if `a`
        // is a prefix of a longer `b`, then `b` must come first or `a` would
        // shadow it. Assert the invariant for every generated word group rather
        // than for specific spellings (which come and go from the tables).
        let mut pairs_checked = 0;
        for group in &model.groups {
            if !matches!(group.kind, MatchKind::Word) || group.members.is_empty() {
                continue;
            }
            let rule = node_name(group.scope, group.kind);
            let alts = word_alternatives(&region, rule);
            for (i, a) in alts.iter().enumerate() {
                for (j, b) in alts.iter().enumerate() {
                    if i != j && b.len() > a.len() && b.starts_with(a.as_str()) {
                        pairs_checked += 1;
                        assert!(
                            j < i,
                            "in `{rule}`, longer `{b}` must precede its prefix `{a}`: {alts:?}"
                        );
                    }
                }
            }
        }
        // events/event, nat/nat1, pow/pow1 all exist, so the loop must have
        // exercised the ordering — guard against the check silently going dark.
        assert!(
            pairs_checked > 0,
            "no prefix pair found to exercise ordering"
        );
    }

    #[test]
    fn symbol_rules_are_string_literals() {
        let model = Model::build();
        let region = render_grammar_region(&model);
        let op_sym = region
            .lines()
            .find(|l| l.trim_start().starts_with("operator_sym:"))
            .expect("operator_sym rule");
        // No regex — exact string literals the lexer's longest-match orders.
        assert!(op_sym.contains("token(choice("));
        assert!(!op_sym.contains("/(?:"));
        assert!(op_sym.contains("\"∈\""));
        assert!(op_sym.contains("\"<=>\""));
    }

    #[test]
    fn js_string_escapes_backslashes() {
        assert_eq!(js_string("\\/"), "\"\\\\/\""); // set union ASCII `\/`
        assert_eq!(js_string("∈"), "\"∈\"");
    }
}
