; Generated by `rossi gen-grammars` from the canonical token tables. Do not edit by hand.
; The captured node names are produced by editors/zed/grammars/tree-sitter-eventb.

(keyword) @keyword
(status_keyword) @keyword
(constant_sym) @constant.builtin
(constant_word) @constant.builtin
(builtin) @function.builtin
(operator_sym) @operator
(operator_word) @operator

(comment) @comment
(string) @string
(number) @number
(label) @label
(identifier) @variable

["(" ")" "[" "]" "{" "}"] @punctuation.bracket
"," @punctuation.delimiter
